### ISSUE TITLE
loose, transition and interference fits in assembly

### ISSUE THREAD

**Issue by kcleung** [Zolko-123/FreeCAD_Assembly4#190]
In order to make the assembly feature useful in real-life engineering applications, It is essential for the asssembly workbench and the assembly data structure to make it mandatory to specify each fit as a loose fit, a transition fit or an interference fit, in particular the amount of interference.

Actually in the wikipedia article on engineering fit:

https://en.wikipedia.org/wiki/Engineering_fit

It appears that within each category, we also need specify the subtypes of the loose, transition and interference fit as well.

For assembly to be of practical use, the system needs to automatically validate all fits within the assembly, and to spot out any errors.  This is essential if we were to use FreeCAD to design a machine, and run automated design rule check and mock assemblies to model out any issues before we spend $$$$$  to make the physical mock-up.  Can this check be done without using a solver?

I feel that this feature would be very important to make the assembly feature adequate for industrial use, and we better get it right before Freecad reaches 1.0

**Comment by Zolko-123** [comment]
This is an interesting question ... in today's implementation, all "fits" are nominal fits, without any specified tolerance. In all the projects that I have been doing, the tolerancing of fits is done at the end, for the final drawings and manufacturing process. We have never done such tolerancing in the assembly at the design process, it was always done at a second stage, after the prototyping and before the serial industrialization, because this depends on the manufacturing process. 

Thank-you for your proposal, but I will close the issue.
