### ISSUE TITLE
BOM-Expansion

### ISSUE THREAD

**Issue by Ediforce44** [Zolko-123/FreeCAD_Assembly4#372]
Hey,
I didn't find a better way to contact someone from this repository :D. So I hope this is the way to go.

I created a little expansion for the BOM mechanism (here [[1]](https://github.com/Ediforce44/FreeCAD-Assembly4-BOM)). I want to ask if you are interested in integrating this directly into Assembly 4.
If so I would help you to make the integration cleaner than it is know, because not everybody needs these features and a option menu would be great.

Story time:
I saw Assembly 2 or so featuring a BOM mechanism which is useful for woodworkers and everyone how build something out of plane parts. So I automized the BOM of A4 to do the same and even more and better for the above usecase ;). I hope you like it.

**Comment by Zolko-123** [comment]
short answer: yes, I'm interested. Please note that there have been quite some improvements and additions in Asm4 BOM recently.

Thinking of various BOM needs and functions, I'd suggest to have a drop-down menu in the toolbar, similar to the fasteners or datum objects menu in the menubar, which would allow to call the chosen BOM function. In this case, "your" BOM would be one of the available options.

Do you think you could make a proposal for such a thing ? (in any case, please make PRs against the development branch and not master)

**Comment by Ediforce44** [comment]
sure. Should I do a separate fork on the repository and contact you if I make progress or how should we handle this?

**Comment by leoheck** [comment]
Have you tried the developer branch? There is this BOM functionality working there.

**Comment by leoheck** [comment]
I came here with another idea to implement in the existing BOM. Wich is a flag to disable internal parts to be added in the BOM.
For instance, I assembled a Motor with Asm4, but I don't want parts of the motor in the BOM, because the motor is a single part since I am not making motors. This thing is missing and I am going to add in the existing BOM system.

**Comment by Ediforce44** [comment]
Nice, I implemented something similar in my version. If the part, model etc. is invisible it would not be included into the BOM. But I think the need for tags is something different since it is permanent and independent from the rendering.

**Comment by Ediforce44** [comment]
Btw I saw you worked a lot on the BOM. So I ask you what do you think about that: I think about a selection menu to select your BOM method for the project. Every BOM method has its own starting function. If you create the BOM by pressing the button the corresponding starting function is called. The starting function will then create a partlist with attributes and the BOM will process this list after the starting function is finished. (Like a strategy design pattern if you know what I mean).

So it would be really easy to add new BOM methods

**Comment by leoheck** [comment]
What if you make a pr proposing something so we can visualize better?

**Comment by Ediforce44** [comment]
I will do it as soon as I have time for it.

**Comment by Zolko-123** [comment]
Hello, I don't know who worked on the BOM, but it was making errors, so I cleaned up a bit (in the development branch). A lot of stuff is still hard-coded (Doc_Label), please use the InfoKeys tables instead.

**Comment by Zolko-123** [comment]
closed, see #395

**Comment by BuhtigithuB** [comment]
> I will do it as soon as I have time for it.

Hi @Ediforce44,

Can we help in testing or some how... I am reading on the issue, and your proposal of having multiples BOM methods come to mind as soon as I stumble on Zolko noticing that the BOM feature perish over time because of divergent needs... That way we could rely  on a working BOM feature.

I saw your video, but I am not sure if applying your mod over current plugin version would work as Zolko mention he makes some clean up...

@Zolko-123, if  @leoheck implementation works can we merge it? Some thing better than no thing... 

:)

**Comment by Ediforce44** [comment]
Sadly I have to say, I couldn't do anything. I have a lot going on in real life and also a lot of exams. I couldn't really follow the newest changes, so I don't know if I could help in any way.
If leoheck has a working version I think it is better to go with his one.

**Comment by leoheck** [comment]
I put the old, existing BOM to work. It was hard and it may have issues, of course, but it works listing important objects. There might be some objects that are missing because each one has to be treated individually. Also, the code can be improved, always. But this is a matter of putting extra time into having this merged in the master to allow people to bring their issues so we can build it incrementally. Having this feature lost in the development branch does not help to improve this because people use to install add-ons with the addon manager. Now the addon manager could have the option to select the branch of the addon. I don't think it has. This could help users to test things easily.
